import React, { useState } from "react";
import { Badge, I, Ico, PageTitle } from "../shared";

const PROVEEDORES = [
  { id: 1, nombre: "Polymer Solutions Inc.", pais: "EE.UU.", contacto: "John Williams", email: "jwilliams@polysol.com", tel: "+1 713 445 8821", leadTime: "35–42 días", estado: "Activo" },
  { id: 2, nombre: "ChemTrade Global LLC", pais: "EE.UU.", contacto: "Sarah Connor", email: "sconnor@chemtrade.com", tel: "+1 832 221 9043", leadTime: "28–35 días", estado: "Activo" },
  { id: 3, nombre: "Pacific Polymers Corp.", pais: "EE.UU.", contacto: "David Park", email: "dpark@pacpoly.com", tel: "+1 206 882 7711", leadTime: "40–50 días", estado: "Activo" },
  { id: 4, nombre: "EcoQuímicos Brasil", pais: "Brasil", contacto: "Felipe Alves", email: "falves@ecobr.com", tel: "+55 11 3344 8899", leadTime: "15–20 días", estado: "Inactivo" },
];

export default function Proveedores() {
  const [showModal, setShowModal] = useState(false);
  return <div><PageTitle title="Proveedores" sub="Directorio de proveedores de materias primas"><button className="btn btn-primary" onClick={() => setShowModal(true)}><Ico p={I.plus} size={14} /> Nuevo proveedor</button></PageTitle><div className="panel"><table className="dt w-full"><thead><tr><th>Empresa</th><th>País</th><th>Contacto</th><th>Email</th><th>Lead Time</th><th>Estado</th><th></th></tr></thead><tbody>{PROVEEDORES.map(provider => <tr key={provider.id}><td style={{ fontWeight: 600, color: "#0F172A" }}>{provider.nombre}</td><td><Badge t="info">{provider.pais}</Badge></td><td><div>{provider.contacto}</div><div style={{ fontSize: "0.6875rem", color: "#94A3B8" }}>{provider.tel}</div></td><td style={{ color: "#0052CC", fontSize: "0.8125rem" }}>{provider.email}</td><td style={{ fontFamily: "JetBrains Mono, monospace", fontSize: "0.75rem", color: "#0052CC", fontWeight: 600 }}>{provider.leadTime}</td><td><Badge t={provider.estado === "Activo" ? "ok" : "neutral"}>{provider.estado}</Badge></td><td><div style={{ display: "flex", gap: 4 }}><button className="btn btn-ghost btn-sm"><Ico p={I.edit} size={13} /></button><button className="btn btn-ghost btn-sm"><Ico p={I.trash} size={13} /></button></div></td></tr>)}</tbody></table></div>{showModal && <div className="modal-backdrop" onClick={() => setShowModal(false)}><div className="modal" style={{ width: 480, padding: 24 }} onClick={event => event.stopPropagation()}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 18 }}><h2 style={{ fontWeight: 700, color: "#0F172A" }}>Nuevo Proveedor</h2><button onClick={() => setShowModal(false)} style={{ background: "none", border: "none", cursor: "pointer", color: "#94A3B8" }}><Ico p={I.x} size={18} /></button></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{[{ l: "Nombre Empresa", s: 2 }, { l: "País", s: 1 }, { l: "Lead Time (días)", s: 1 }, { l: "Contacto", s: 1 }, { l: "Teléfono", s: 1 }, { l: "Email", s: 2 }].map(field => <div key={field.l} className="field" style={{ gridColumn: `span ${field.s}` }}><label className="label">{field.l}</label><input className="input" placeholder={field.l} /></div>)}</div><div style={{ display: "flex", gap: 8, marginTop: 18 }}><button className="btn btn-primary" style={{ flex: 1, justifyContent: "center" }} onClick={() => setShowModal(false)}><Ico p={I.check} size={14} /> Guardar</button><button className="btn btn-ghost" onClick={() => setShowModal(false)}>Cancelar</button></div></div></div>}</div>;
}
